### ISSUE TITLE
`v-model` (& generic directive) scope name

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/Vue#20]
I'm not happy with the current `v-model` scope of `keyword.control.directive`.
`v-model` is syntactic sugar for 
```
  :modelValue="foo"
  @update:modelValue="$event => (foo = $event)"
```
, where the former is a `v-bind` and the latter a `v-on`. However, neither `modelValue` nor `update:modelValue` are scoped as a `keyword`, which is correct. 

Furthermore, I believe the generic directives should not be scoped `keyword.control` because they do not affect control flow like `v-for` or `v-if` do. Control flow keywords are more important than others, imo, which is why I have a rule for them in my color scheme.

Instead, we could consider utilizing a `support` scope or a generic `keyword.other.directive`.

I'm undecided on which scope to choose for`v-model` specifically since it has a known and defined meaning but I can't remember a fitting scope name for it outside of my generic directive proposal.

**Comment by deathaxe** [comment]
I find `keyword.other.directive` quite suitable as we keep in keyword scope for all `v-` attributes/directives but still clearly distinguish normal from control flow keywords.

Would it make sense to scope `v-bind` and `v-model` as `keyword.declaration` as they somehow define/declare data bindings?

**Comment by FichteFoll** [comment]
Definitely not for `v-bind` since that is a parameter name rather than a (local) declaration. You can't use the thing you declared there in your current component.

For `v-model`, the situation is slightly different because you're also not declaring something there but rather providing a variable as an in-out parameter, so it's still just a (mutable) reference. Going with the closest analogy, I suppose we could use [C#'s `out` keyword](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out) as a reference. That is currently scoped as `storage.modifier.parameter` and I think a `storage.modifier` scope *is* reasonable here.

**Comment by FichteFoll** [comment]
Ah, but then there is also a form of v-model with parameters, which I keep forgetting the syntax of because it's new in 3.4 and I can't use it in my projects. ( :cry: ) https://vuejs.org/guide/components/v-model.html#v-model-arguments

In this form, a model name is added to the `v-model` directive as `v-model:title="someTitle"`. That *could* be scoped as a paramter variable (like in a python function call with a keyword argument) but would also not be symmetric with a standard one-way `:title="someTitle"` anymore, if we change that back to just an attribute.

**Comment by deathaxe** [comment]
Now that we dropped `variable.parameter` I am not sure we want to add it back for individual directives. Maybe we shouldn't add too much semantic detail in favor of consistent and expectable syntax highlighting and keeping noise low.

As normal modifiers `.mod` are scoped `storage.modifier` I would also not apply that scope to `v-model`. May look odd and unexpected.

Than it is just another vue directive as all the others except control flow.

**Comment by FichteFoll** [comment]
Indeed, adding back the `variable` scope would be wrong. 

I think what we have now with `keyword.other` for all non control flow directives is fine.
