### ISSUE TITLE
Colons in `v-on`/`@` attributes

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/Vue#21]
The colon in the attribute `@update:modelValue` is scoped as `keyword.control.directive` but it's technically just an arbitrary name for the emitted event and should thus be part of the same scope as the surrounding words `update` and `modalValue`, which is `variable.parameter`.

**Comment by deathaxe** [comment]
Syntax currently follows the naming scheme of https://vuejs.org/guide/essentials/template-syntax.html#modifiers, which uses `:` as delimiter for directive name and parameter.

Hence `:` and `.` are excluded from identifiers. As `@` is already an appreviation another `:` is assumed not being allowed.

Hence attribute name stops at after `@update`. `:modelValue` is then treated as appreviated `v-bind:`.
