### ISSUE TITLE
Odd conflict with JavaScriptNext - ES6 Syntax package

### ISSUE THREAD

**Issue by Steve-OH** [SublimeText/Vue#43]
(This is more of a heads-up than a real issue.)

There is a conflict between the latest release of this package and the (obsolete?) **JavaScriptNext - ES6 Syntax** package. Opening a `.vue` file when both are installed results in an error message:

> Error loading syntax file "Packages/Vue/Vue Component.sublime-syntax": Packages/Vue/Vue Component.sublime-syntax: no such target scope:source.js#expression

The workaround is to remove the **JavaScriptNext - ES6 Syntax** package.

**Comment by FichteFoll** [comment]
Indeed, the Vue package is designed to work with the Default `JavaScript` package and not third-parties. This also comes with the reason that the default JS syntax is the best one out there and any potential improvements should be made to that instead of forking, thus benefitting everyone.

**Comment by deathaxe** [comment]
Syntax was added as possible trouble maker to README in be67bf228e616fd5e335315f0dfc8e4e3e11db25.
